# consider removing some bits from offspring_functions and putting them in here directly
# i.e. maybe all that offspring_functions do is calculate number of offspring produced? Or
#      number of offspring, infection times, class, location etc?
## yeah we need to decide on some principled and functional delineation of which offspring information
## is generated in the offspring_functions themselves, and which information is generated by the complete_offspring_info
## maybe the offspring functions should just produce info on 1) when, where, who etc is infected; and 2) everything downstream
## of the infection event itself (natural history, timings etc) are handled in the "complete_offspring_info" function? Maybe.
## Check which rescue probability we need to be using for death in comm vs hosp
## need to add funeral safety info in here I think
complete_offspring_info <- function(
    ## Parent and offspring information
    parent_info = NULL,                  ## parent information (row from the main dataframe)
    offspring_dataframe = NULL,          ## offspring dataframe generated by the offspring functions

    ## Probabilities of different outcomes. All hospitalisation/death
    ## probabilities below are CONDITIONAL on the offspring being symptomatic
    ## (asymptomatic offspring cannot die or be hospitalised in this model).
    prob_symptomatic = NULL,             ## P(symptomatic | infected)
    prob_hospitalised_hcw = NULL,        ## scalar or function(t): P(hospitalised | symptomatic) for HCWs
    prob_hospitalised_genPop = NULL,     ## scalar or function(t): P(hospitalised | symptomatic) for genPop
    prob_death_comm = NULL,              ## P(die | symptomatic, community) — conditional CFR for non-hospitalised symp cases
    prob_death_hosp = NULL,              ## P(die | symptomatic, hospitalised) — conditional CFR for hospitalised cases; must be <= prob_death_comm

    ## Funeral occurrence
    p_unsafe_funeral_comm_hcw = NULL,    ## scalar or function(t): probability of unsafe funeral after a community death, HCW
    p_unsafe_funeral_hosp_hcw = NULL,    ## scalar or function(t): probability of unsafe funeral after a hospital death, HCW
    p_unsafe_funeral_comm_genPop = NULL, ## scalar or function(t): probability of unsafe funeral after a community death, genPop
    p_unsafe_funeral_hosp_genPop = NULL, ## scalar or function(t): probability of unsafe funeral after a hospital death, genPop

    ## Contact tracing consequences. `traced` arrives on the offspring dataframe from the
    ## offspring functions (a contact's tier determines how likely it was to be traced).
    ## Traced cases may be admitted sooner and more often. Both default to no effect.
    onset_to_hospitalisation_traced = NULL,    ## scalar or function(t): flat onset-to-admission delay for traced cases (caps their own delay); NULL = no effect
    prob_hospitalised_traced = NULL,           ## scalar or function(t): ABSOLUTE P(hospitalised | symptomatic) for traced cases; NULL = no effect
    prob_hospitalised_multiplier_traced = 1,   ## scalar or function(t): multiplier on P(hospitalised | symptomatic) for traced cases (ignored if the absolute is set)

    ## Delay distributions
    incubation_period,                   ## between infection occurring and symptoms occurring (in symptomatic individuals)
    onset_to_hospitalisation,            ## between symptom onset and hospitalisation
    hospitalisation_delay_factor = 1.0,  ## scalar or function(t): multiplier on onset_to_hospitalisation draws
    hospitalisation_to_death,            ## between hospitalisation and death (in those dying in hospital)
    hospitalisation_to_recovery,         ## between hospitalisation and recovery (in those recovering in hospital)
    onset_to_death,                      ## between symptom onset and death (for those dying in community)
    onset_to_recovery                    ## between symptom onset and recovery (for those recovering in community)
)
{

  ## Small local helpers keep the implementation backwards-compatible with
  ## scalar parameters while allowing the same arguments to be supplied as
  ## functions of calendar time, usually from make_time_varying().
  validate_probability_or_time_varying <- function(param, param_name) {
    if (is.function(param)) {
      return(invisible(NULL))
    }
    if (!is.numeric(param) || length(param) != 1L || is.na(param) || param < 0 || param > 1) {
      stop(sprintf("`%s` must be a function(t) or a single numeric in [0, 1].", param_name),
           call. = FALSE)
    }
    invisible(NULL)
  }

  validate_positive_or_time_varying <- function(param, param_name) {
    if (is.function(param)) {
      return(invisible(NULL))
    }
    if (!is.numeric(param) || length(param) != 1L || is.na(param) || param <= 0) {
      stop(sprintf("`%s` must be a function(t) or a single positive numeric.", param_name),
           call. = FALSE)
    }
    invisible(NULL)
  }

  resolve_probability <- function(param, t, param_name) {
    value <- resolve_time_varying(param = param, t = t, param_name = param_name)
    if (any(value < 0 | value > 1)) {
      stop(sprintf("`%s` must resolve to value(s) in [0, 1].", param_name), call. = FALSE)
    }
    value
  }

  resolve_positive <- function(param, t, param_name) {
    value <- resolve_time_varying(param = param, t = t, param_name = param_name)
    if (any(value <= 0)) {
      stop(sprintf("`%s` must resolve to positive value(s).", param_name), call. = FALSE)
    }
    value
  }

  validate_probability_or_time_varying(prob_hospitalised_hcw, "prob_hospitalised_hcw")
  validate_probability_or_time_varying(prob_hospitalised_genPop, "prob_hospitalised_genPop")
  validate_positive_or_time_varying(hospitalisation_delay_factor, "hospitalisation_delay_factor")
  validate_probability_or_time_varying(p_unsafe_funeral_comm_hcw, "p_unsafe_funeral_comm_hcw")
  validate_probability_or_time_varying(p_unsafe_funeral_hosp_hcw, "p_unsafe_funeral_hosp_hcw")
  validate_probability_or_time_varying(p_unsafe_funeral_comm_genPop, "p_unsafe_funeral_comm_genPop")
  validate_probability_or_time_varying(p_unsafe_funeral_hosp_genPop, "p_unsafe_funeral_hosp_genPop")
  validate_positive_or_time_varying(prob_hospitalised_multiplier_traced, "prob_hospitalised_multiplier_traced")
  if (!is.null(prob_hospitalised_traced)) {
    validate_probability_or_time_varying(prob_hospitalised_traced, "prob_hospitalised_traced")
  }
  if (!is.null(onset_to_hospitalisation_traced) && !is.function(onset_to_hospitalisation_traced) &&
      (!is.numeric(onset_to_hospitalisation_traced) || length(onset_to_hospitalisation_traced) != 1L ||
       is.na(onset_to_hospitalisation_traced) || onset_to_hospitalisation_traced < 0)) {
    stop("`onset_to_hospitalisation_traced` must be NULL, a function(t), or a single non-negative numeric value.",
         call. = FALSE)
  }

  ## Delays may legitimately be zero (same-day admission), so they get their own resolver
  ## rather than reusing the strictly-positive one.
  resolve_nonneg <- function(param, t, param_name) {
    value <- resolve_time_varying(param = param, t = t, param_name = param_name)
    if (any(!is.finite(value)) || any(value < 0)) {
      stop(sprintf("`%s` must resolve to finite, non-negative value(s).", param_name), call. = FALSE)
    }
    value
  }

  ## Step 0: Note on parameter interpretation
  ## prob_death_comm, prob_death_hosp, prob_hospitalised_hcw, and
  ## prob_hospitalised_genPop are all CONDITIONAL on the offspring being
  ## symptomatic (P(event | symptomatic, route)). Asymptomatic offspring
  ## cannot die or be hospitalised in this model, which is enforced
  ## structurally by indexing the rbinom draws below on offspring_symptomatic.
  ## The pre-#52 helper conversions (prob / prob_symptomatic) have been removed
  ## because they treated these parameters as unconditional, which conflicted
  ## with how the seeding logic in branching_process_main uses them.
  ## Upfront sanity checks (in branching_process_main) verify the relationship
  ## prob_death_hosp(t) <= prob_death_comm(t) so the second-chance ratio
  ## stays in [0, 1] across the simulation horizon.

  ################################################################################################################################
  ## Step 1: Deciding whether the offspring cases are symptomatic, and if so, when they develop symptoms
  ##  - In this section, we first generate incubation periods for every infection, then decide who is symptomatic, and then use
  ##    the incubation period as the delay between infection and symptom onset if the infectee is symptomatic.
  ## Note: Incubation period isn't used otherwise, and so this section could be streamlined in subsequent versions potentially.
  ################################################################################################################################
  num_offspring <- nrow(offspring_dataframe)
  offspring_incubation_period <- incubation_period(n = num_offspring)                                         ## drawing incubation period times from the incubation period distribution
  offspring_symptomatic <- as.logical(rbinom(n = num_offspring, size = 1, prob = prob_symptomatic))           ## calculating whether offspring are symptomatics
  offspring_time_symptom_onset <- rep(NA_real_, num_offspring)
  offspring_time_symptom_onset[offspring_symptomatic] <- offspring_incubation_period[offspring_symptomatic]   ## populating vector of symptom onset times with incubation period for symptomatic offspring

  ## Compute absolute infection and symptom-onset times for each offspring.
  ## These are the "clock" times used to resolve time-varying parameters. The
  ## infection clock must include each offspring's infection time relative to the
  ## parent, not just the parent's infection time.
  offspring_absolute_infection_time <- parent_info$time_infection_absolute + offspring_dataframe$time_infection_relative
  offspring_absolute_symptom_time <- offspring_absolute_infection_time + offspring_incubation_period

  ################################################################################################################################
  ## Step 1b: Contact tracing status
  ##  - `traced` is carried on the offspring dataframe by the offspring functions: whether a contact was reached by tracing
  ##    depends on its risk tier, so this is the channel by which the risk structure drives the NPIs.
  ##  - Its consequences land in Step 2 below: a traced case is admitted sooner, and possibly more often.
  ##  - The replay path used for OBV's prevented-infection counterfactual builds its offspring frame without this column,
  ##    so default it to FALSE rather than requiring it.
  ################################################################################################################################
  offspring_traced <- if (is.null(offspring_dataframe$traced)) {
    rep(FALSE, num_offspring)
  } else {
    as.logical(offspring_dataframe$traced) & !is.na(offspring_dataframe$traced)
  }

  ################################################################################################################################
  ## Step 2: Deciding whether symptomatic offspring are potentially hospitalised
  ##  - In this section, we calculate the potential hospitalisation status for the (symptomatic) offspring cases, i.e. whether they would
  ##    all other factors notwithstanding, visit hospital. In the subsequent section, we will see whether they are *actually* hospitalised
  ##    (i.e. check they don't die/recover before they would) otherwise be hospitalised.
  ################################################################################################################################
  ## For each symptomatic offspring, determine hospitalisation probability at
  ## that offspring's calendar time of symptom onset. HCW and genPop parameters
  ## remain separate, even if the same trajectory is supplied to both. Under
  ## the conditional-CFR interpretation (see Step 0), the resolved value IS
  ## P(hospitalised | symptomatic) directly, so no further conversion is needed.
  symptomatic_indices <- which(offspring_symptomatic)
  prob_hosp <- numeric(length(symptomatic_indices))

  for (i in seq_along(symptomatic_indices)) {
    si <- symptomatic_indices[i]
    t_onset <- offspring_absolute_symptom_time[si]

    if (offspring_dataframe$class[si] == "HCW") {
      prob_hosp[i] <- resolve_probability(prob_hospitalised_hcw, t_onset, "prob_hospitalised_hcw")
    } else {
      prob_hosp[i] <- resolve_probability(prob_hospitalised_genPop, t_onset, "prob_hospitalised_genPop")
    }

    ## Traced cases may present more readily, specified either as an absolute
    ## probability (which replaces the untraced value outright) or as a multiplier on
    ## it. The absolute wins when both are given; both default to no effect.
    if (offspring_traced[si]) {
      if (!is.null(prob_hospitalised_traced)) {
        prob_hosp[i] <- resolve_probability(prob_hospitalised_traced, t_onset,
                                            "prob_hospitalised_traced")
      } else {
        hosp_mult <- resolve_positive(prob_hospitalised_multiplier_traced, t_onset,
                                      "prob_hospitalised_multiplier_traced")
        prob_hosp[i] <- min(prob_hosp[i] * hosp_mult, 1)
      }
    }
  }

  offspring_potentially_hosp <- rep(FALSE, num_offspring)
  offspring_potentially_hosp[offspring_symptomatic] <- as.logical(rbinom(n = sum(offspring_symptomatic), size = 1, prob = prob_hosp)) # assigning potential hospitalisation status; asymptomatics aren't hospitalised, so only update vector for symptomatics
  offspring_potentially_hosp_time <- rep(NA_real_, num_offspring)
  ## Draw raw hospitalisation delays and apply the delay factor resolved at each
  ## potentially hospitalised offspring's symptom-onset time.
  raw_hosp_delays <- onset_to_hospitalisation(n = sum(offspring_potentially_hosp))
  hosp_indices <- which(offspring_potentially_hosp)
  delay_factors <- resolve_positive(hospitalisation_delay_factor,
                                    offspring_absolute_symptom_time[hosp_indices],
                                    "hospitalisation_delay_factor")
  hosp_delays <- raw_hosp_delays * delay_factors

  ## Traced cases are admitted a flat `onset_to_hospitalisation_traced` days after symptom
  ## onset. This CAPS their delay rather than replacing it: tracing can only speed a case up,
  ## never hold back someone who would have presented sooner on their own. Note that faster
  ## admission also raises the REALISED hospitalisation rate, because admission is more likely
  ## to beat the community outcome (Step 3.2) -- an effect on top of any explicit
  ## prob_hospitalised_multiplier_traced.
  if (!is.null(onset_to_hospitalisation_traced) &&
      length(hosp_indices) > 0 && any(offspring_traced[hosp_indices])) {
    traced_hosp <- offspring_traced[hosp_indices]
    traced_delay <- resolve_nonneg(onset_to_hospitalisation_traced,
                                   offspring_absolute_symptom_time[hosp_indices[traced_hosp]],
                                   "onset_to_hospitalisation_traced")
    hosp_delays[traced_hosp] <- pmin(hosp_delays[traced_hosp], traced_delay)
  }
  offspring_potentially_hosp_time[offspring_potentially_hosp] <- hosp_delays

  ################################################################################################################################
  ## Step 3: Deciding on the outcome for the offspring cases, and if so, when that outcome occurs
  ##  - In this section, we calculate the outcome for the offspring (recovery or death), when this occurs and where this occurs (community or healthcare).
  ##    It's here we see whether a "potential" hospitalisation is *actually* hospitalised i.e. we check that they don't recover/die before they
  ##    would access healthcare.
  ##  - This section was hard to code because time-to-event shapes hospitalisation (i.e. whether or not someone is hospitalised successfully) but also
  ##    hospitalisation shapes time-to-outcome (i.e. we have diff distributions for time-to-outcome dependent on whether someone is hospitalised).
  ##    We therefore start by assuming a community outcome, see when that event occurs (and what it is) and see if it precludes hospitalisation. If it
  ##    does, the infection remains a community one. If it doesn't, we say they are admitted - if the individual would have recovered in the community,
  ##    we assume they also recover in hospital. If they would have died in the community, we assume they have a "chance" at being saved by the healthcare.
  ################################################################################################################################

  ## 3.1 For all offspring, we start by assuming a community outcome, and calculate which event (recovery or death) occurs and when it occurs.
  ## Under the conditional-CFR interpretation, prob_death_comm IS P(die | symp, community)
  ## directly — no further conversion is applied. Asymptomatic offspring stay FALSE.
  temp_comm_outcome_death <- rep(FALSE, num_offspring)
  temp_comm_outcome_death[offspring_symptomatic] <-  as.logical(rbinom(n = sum(offspring_symptomatic), size = 1, prob = prob_death_comm))  ## only symptomatic offspring can die
  temp_comm_outcome_time <- rep(NA_real_, num_offspring)
  temp_comm_outcome_time[temp_comm_outcome_death] <- onset_to_death(n = sum(temp_comm_outcome_death))      ## for those dying, when do they die
  temp_comm_outcome_time[!temp_comm_outcome_death] <- onset_to_recovery(n = sum(!temp_comm_outcome_death)) ## for those recovering, when do they recovering

  ## 3.2 For those offspring who *could* hospitalised (i.e. potentially hospitalised in Step 2), if the community outcome occurs earlier than their potential hospitalisation,
  ##     we just keep the community outcome (which occurs earlier than hospitalisation and thus precludes it); if hospitalisation precedes the community outcome, hospitalisation is successful.
  ##     If they are successfully hospitalised and the community outcome was a recovery, we assume they also recover in hospital. If the community outcome was death,
  ##     we them give another "chance" to be saved at the hospital.
  ##
  ## Under the conditional-CFR interpretation: among symptomatic hospitalised offspring,
  ## P(would-die-in-community | symp) = prob_death_comm and second_chance = prob_death_hosp / prob_death_comm.
  ## The realised hospital CFR is then prob_death_comm * (prob_death_hosp / prob_death_comm) = prob_death_hosp,
  ## as intended by the docstring. branching_process_main's upfront sanity check ensures
  ## prob_death_hosp <= prob_death_comm so the ratio stays in [0, 1].
  hosp_success <- offspring_potentially_hosp_time[offspring_potentially_hosp] < temp_comm_outcome_time[offspring_potentially_hosp] # checking whether community outcome occurs before potential hospitalisation
  second_chance_death_prob <- prob_death_hosp / prob_death_comm
  hosp_outcome <- temp_comm_outcome_death[offspring_potentially_hosp][hosp_success] # subsetting all offspring by those potentially hospitalised, and then the subset of those who actually are
  hosp_outcome[which(hosp_outcome)] <- as.logical(rbinom(n = sum(hosp_outcome), size = 1, prob = second_chance_death_prob)) # for those who would die in hospital (i.e. hosp_outcome == TRUE), give them a second chance

  ## 3.3 Generating the final information for all offspring to be inputted into the offspring dataframe
  ## Generating the vector of actual hospitalisation status and associated times (if hospitalised)
  offspring_actually_hosp <- offspring_potentially_hosp
  offspring_actually_hosp[offspring_potentially_hosp] <- hosp_success
  offspring_actually_hosp_time <- rep(NA_real_, num_offspring)
  offspring_actually_hosp_time[offspring_actually_hosp] <- offspring_potentially_hosp_time[offspring_actually_hosp] ## filling this vector in with hosp times for those successfully hopspitalised

  ## Generating the vector of actual outcome and associated times
  offspring_outcome <- temp_comm_outcome_death
  offspring_outcome[offspring_actually_hosp] <- hosp_outcome   ## replacing community outcomes for those successfully hospitalised
  offspring_outcome_time <- rep(NA_real_, num_offspring)
  offspring_outcome_time[!offspring_actually_hosp] <- temp_comm_outcome_time[!offspring_actually_hosp] ## for those not hospitalised, just use the community time generated above
  hosp_and_death <- offspring_outcome & offspring_actually_hosp   ## temp vectors to help subset those hospitalised and who die
  hosp_and_recover <-!offspring_outcome & offspring_actually_hosp ## temp vectors to help subset those hospitalised and who recover
  offspring_outcome_time[hosp_and_death] <- offspring_potentially_hosp_time[hosp_and_death] + hospitalisation_to_death(n = sum(hosp_and_death))
  offspring_outcome_time[hosp_and_recover] <- offspring_potentially_hosp_time[hosp_and_recover] + hospitalisation_to_recovery(n = sum(hosp_and_recover))

  ## Generating the vector of where the outcome occurs
  offspring_outcome_location <- rep("community", num_offspring)
  offspring_outcome_location[offspring_actually_hosp] <- "hospital"

  ################################################################################################################################
  ## Step 4: Generating funeral status for those who die (i.e. whether it's safe or not)
  ##
  ##
  ################################################################################################################################
  hosp_and_death_and_hcw <- offspring_outcome & offspring_actually_hosp & offspring_dataframe$class == "HCW"        ## those hcw who die and who were hospitalised
  hosp_and_death_and_genPop <- offspring_outcome & offspring_actually_hosp & offspring_dataframe$class == "genPop"  ## those genPop who die and who were hospitalised
  comm_and_death_and_hcw <- offspring_outcome & !offspring_actually_hosp & offspring_dataframe$class == "HCW"       ## those hcw who die and who do so in the community
  comm_and_death_and_genPop <- offspring_outcome & !offspring_actually_hosp & offspring_dataframe$class == "genPop" ## those genPop who die and who do so in the community

  ## Death-time clock for time-varying funeral safety probabilities.
  ## offspring_outcome_time is measured from symptom onset; add incubation period
  ## and absolute infection time to obtain absolute calendar death/recovery time.
  offspring_absolute_outcome_time <- offspring_absolute_infection_time + offspring_incubation_period + offspring_outcome_time

  draw_funeral_safety <- function(idx, prob_unsafe_funeral, param_name) {
    if (!any(idx)) {
      return(character(0))
    }
    p_unsafe_funeral_t <- resolve_probability(prob_unsafe_funeral,
                                              offspring_absolute_outcome_time[idx],
                                              param_name)
    ifelse(rbinom(n = sum(idx), size = 1, prob = p_unsafe_funeral_t) == 1,
           "unsafe", "safe")
  }

  offspring_funeral_safety <- rep(NA_character_, num_offspring)
  offspring_funeral_safety[hosp_and_death_and_hcw] <- draw_funeral_safety(hosp_and_death_and_hcw,
                                                                          p_unsafe_funeral_hosp_hcw,
                                                                          "p_unsafe_funeral_hosp_hcw")
  offspring_funeral_safety[hosp_and_death_and_genPop] <- draw_funeral_safety(hosp_and_death_and_genPop,
                                                                             p_unsafe_funeral_hosp_genPop,
                                                                             "p_unsafe_funeral_hosp_genPop")
  offspring_funeral_safety[comm_and_death_and_hcw] <- draw_funeral_safety(comm_and_death_and_hcw,
                                                                          p_unsafe_funeral_comm_hcw,
                                                                          "p_unsafe_funeral_comm_hcw")
  offspring_funeral_safety[comm_and_death_and_genPop] <- draw_funeral_safety(comm_and_death_and_genPop,
                                                                             p_unsafe_funeral_comm_genPop,
                                                                             "p_unsafe_funeral_comm_genPop")

  ################################################################################################################################
  ## Step 5: Update and output offspring dataframe
  ################################################################################################################################
  offspring_dataframe$parent <-                             parent_info$id
  offspring_dataframe$generation <-                         parent_info$generation + 1
  offspring_dataframe$time_infection_absolute <-            parent_info$time_infection_absolute + offspring_dataframe$time_infection_relative
  offspring_dataframe$incubation_period <-                  offspring_incubation_period
  offspring_dataframe$symptomatic <-                        offspring_symptomatic
  offspring_dataframe$time_symptom_onset_relative <-        offspring_time_symptom_onset
  offspring_dataframe$time_symptom_onset_absolute <-        offspring_dataframe$time_infection_absolute + offspring_dataframe$time_symptom_onset_relative
  offspring_dataframe$hospitalisation <-                    offspring_actually_hosp
  offspring_dataframe$time_hospitalisation_relative <-      offspring_incubation_period + offspring_actually_hosp_time
  offspring_dataframe$time_hospitalisation_absolute <-      offspring_dataframe$time_infection_absolute + offspring_dataframe$time_hospitalisation_relative
  offspring_dataframe$outcome <-                            offspring_outcome
  offspring_dataframe$outcome_location <-                   offspring_outcome_location
  offspring_dataframe$time_outcome_relative <-              offspring_incubation_period + offspring_outcome_time
  offspring_dataframe$time_outcome_absolute <-              offspring_dataframe$time_infection_absolute + offspring_dataframe$time_outcome_relative
  offspring_dataframe$funeral_safety <-                     offspring_funeral_safety
  offspring_dataframe$traced <-                             offspring_traced
  offspring_dataframe$n_offspring <-                        rep(NA_integer_, num_offspring)
  offspring_dataframe$offspring_generated <-                rep(FALSE, num_offspring)

  ## Step 5: Return completed dataframe
  return(offspring_dataframe)

}
